server:
  port: 8085

spring:
  application:
    name: statistics

  banner:
    location: banner/banner-${spring.profiles.active}.txt

  profiles:
    active: local
    include: datasource


logging:
  level:
    co.kr.statistics: DEBUG
    org.hibernate.SQL: DEBUG
